name: github pages

on:
  push:
    branches: [ dev ]
  # release:
  #   types:
  #     - created

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: NOLOSAY
        uses: actions/checkout@v2
      - run: yarn rw build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./web/dist